name: rex_fluttercon_eu_2024
description: "REX from the FlutterCon Europe 2024"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.15.0
  go_router: ^13.2.5

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/